#pragma once

// generated by tools/ddl2cpp sql/schema.sql server/src/dao/schema model

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace model {
namespace User_ {
struct Id {
    struct _alias_t {
        static constexpr const char _literal[] = "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template <typename T>
        struct _member_t {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
        };
    };
    using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
};
struct Username {
    struct _alias_t {
        static constexpr const char _literal[] = "username";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template <typename T>
        struct _member_t {
            T username;
            T& operator()() { return username; }
            const T& operator()() const { return username; }
        };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
};
struct Password {
    struct _alias_t {
        static constexpr const char _literal[] = "password";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template <typename T>
        struct _member_t {
            T password;
            T& operator()() { return password; }
            const T& operator()() const { return password; }
        };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
};
}  // namespace User_

struct User : sqlpp::table_t<User, User_::Id, User_::Username, User_::Password> {
    struct _alias_t {
        static constexpr const char _literal[] = "user";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template <typename T>
        struct _member_t {
            T user;
            T& operator()() { return user; }
            const T& operator()() const { return user; }
        };
    };
};
}  // namespace model
